# Generated by Django 5.2.8 on 2025-12-08 08:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FeeStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=100, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('age', models.IntegerField()),
                ('parent_name', models.CharField(max_length=200)),
                ('phone_number', models.CharField(max_length=20)),
                ('parent_id_number', models.CharField(blank=True, max_length=50, null=True)),
                ('class_level', models.CharField(choices=[('Form1', 'Form1'), ('Form2', 'Form2'), ('Form3', 'Form3'), ('Form4', 'Form4')], max_length=50)),
                ('date_registered', models.DateTimeField(auto_now_add=True)),
                ('status', models.BooleanField(default=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='student_photos/')),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('admission_number', models.CharField(blank=True, max_length=10, null=True, unique=True)),
                ('feestructure', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='students.feestructure')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_paid', models.DateTimeField(auto_now_add=True)),
                ('method', models.CharField(default='Cash', max_length=50)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student')),
            ],
        ),
    ]
