# Generated by Django 5.2.8 on 2025-12-15 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0007_feestructure_school_payment_school_student_school'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feestructure',
            name='school',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='school',
        ),
        migrations.RemoveField(
            model_name='student',
            name='school',
        ),
    ]
