# Generated by Django 5.2.8 on 2025-12-18 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0009_payment_checkout_request_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='school_logos/')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
