# Generated by Django 5.2.8 on 2025-12-18 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0010_school'),
    ]

    operations = [
        migrations.DeleteModel(
            name='School',
        ),
    ]
