# Generated by Django 5.2.8 on 2025-12-24 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0016_attendancealert'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancealert',
            name='sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='attendancealert',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('reviewed', 'Reviewed'), ('sent', 'Sent')], default='new', max_length=20),
        ),
    ]
