# Generated by Django 5.2.8 on 2025-12-24 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0017_attendancealert_sent_at_alter_attendancealert_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancealert',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('reviewed', 'Reviewed')], default='new', max_length=20),
        ),
    ]
