# Generated by Django 5.2.8 on 2025-12-30 09:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0020_adminactionlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubjectResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100)),
                ('marks', models.IntegerField()),
                ('grade', models.CharField(max_length=2)),
                ('teacher_comment', models.TextField(blank=True)),
                ('term', models.CharField(choices=[('MID', 'Midterm'), ('END', 'End Term')], max_length=3)),
                ('year', models.IntegerField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student')),
            ],
        ),
        migrations.CreateModel(
            name='TermReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(max_length=10)),
                ('total_score', models.IntegerField()),
                ('position', models.IntegerField(blank=True, null=True)),
                ('remarks', models.TextField()),
                ('year', models.IntegerField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student')),
            ],
        ),
    ]
