# Generated by Django 5.2.8 on 2025-12-30 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0021_subjectresult_termreport'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='termreport',
            name='student',
        ),
        migrations.DeleteModel(
            name='SubjectResult',
        ),
        migrations.DeleteModel(
            name='TermReport',
        ),
    ]
