# Generated by Django 5.2.8 on 2025-12-31 05:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0022_remove_termreport_student_delete_subjectresult_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(choices=[('MID', 'Mid Term'), ('END', 'End Term')], max_length=3)),
                ('total_score', models.IntegerField()),
                ('grade', models.CharField(max_length=5)),
                ('teacher_comment', models.TextField()),
                ('headteacher_remark', models.TextField(blank=True)),
                ('is_published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student')),
            ],
        ),
    ]
