# Generated by Django 5.2.8 on 2025-12-31 05:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0023_academicreport'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('marks', models.IntegerField()),
                ('grade', models.CharField(max_length=5)),
                ('teacher_comment', models.TextField(blank=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='students.academicreport')),
            ],
        ),
    ]
