# Generated by Django 5.2.8 on 2025-12-31 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0025_student_parent_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='academicreport',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('PUBLISHED', 'Published')], default='DRAFT', max_length=20),
        ),
    ]
