# Generated by Django 5.2.8 on 2025-12-31 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0026_academicreport_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='parent_user',
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('class_level', models.CharField(choices=[('Grade1', 'Grade1'), ('Grade2', 'Grade2'), ('Grade3', 'Grade3'), ('Grade4', 'Grade4'), ('Grade5', 'Grade5'), ('Grade6', 'Grade6'), ('Grade7', 'Grade7'), ('Grade8', 'Grade8'), ('Form1', 'Form1'), ('Form2', 'Form2'), ('Form3', 'Form3'), ('Form4', 'Form4')], max_length=50)),
            ],
            options={
                'unique_together': {('name', 'class_level')},
            },
        ),
    ]
