# Generated by Django 5.2.8 on 2025-12-31 09:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0027_remove_student_parent_user_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportsubject',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='students.subject'),
        ),
        migrations.AlterField(
            model_name='reportsubject',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
