# Generated by Django 5.2.8 on 2026-01-18 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0028_reportsubject_subject_alter_reportsubject_name'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='subject',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='subject',
            name='class_level',
        ),
    ]
