# Generated by Django 5.2.8 on 2026-01-18 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0029_alter_subject_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='subject',
            unique_together={('name',)},
        ),
    ]
