# Generated by Django 5.2.8 on 2026-01-18 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0031_message'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
    ]
