# Generated by Django 5.2.8 on 2026-01-27 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0032_delete_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='academicreport',
            name='is_published',
        ),
        migrations.AddField(
            model_name='academicreport',
            name='exam_type',
            field=models.CharField(choices=[('MID', 'Mid Term'), ('END', 'End Term')], default='MID', max_length=3),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='academicreport',
            name='term',
            field=models.CharField(choices=[('T1', 'Term 1'), ('T2', 'Term 2'), ('T3', 'Term 3')], max_length=2),
        ),
    ]
