# Generated by Django 5.2.8 on 2026-01-28 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0033_remove_academicreport_is_published_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reportsubject',
            name='grade',
        ),
    ]
