# Generated by Django 5.2.8 on 2026-02-02 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0035_alter_student_class_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportsubject',
            name='grade',
            field=models.CharField(blank=True, max_length=5),
        ),
    ]
