# Generated by Django 5.2.8 on 2026-02-02 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0036_reportsubject_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='academicreport',
            name='mean_marks',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='academicreport',
            name='total_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='reportsubject',
            name='marks',
            field=models.IntegerField(default=0),
        ),
    ]
