# Generated by Django 5.2.8 on 2026-02-02 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0037_academicreport_mean_marks_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reportsubject',
            name='name',
        ),
        migrations.AlterField(
            model_name='academicreport',
            name='grade',
            field=models.CharField(blank=True, max_length=5),
        ),
    ]
