# Generated by Django 5.2.8 on 2026-02-03 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0038_remove_reportsubject_name_alter_academicreport_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportsubject',
            name='mean_marks',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='reportsubject',
            name='position',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
