# Generated by Django 5.2.8 on 2026-02-03 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0039_reportsubject_mean_marks_reportsubject_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academicreport',
            name='exam_type',
            field=models.CharField(choices=[('MID', 'Mid Term'), ('END', 'End Term')], default='MID', max_length=3),
        ),
    ]
