# Generated by Django 5.2.8 on 2026-02-05 10:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0040_alter_academicreport_exam_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='extra_teachers',
            field=models.ManyToManyField(blank=True, related_name='extra_students', to=settings.AUTH_USER_MODEL),
        ),
    ]
