# Generated by Django 5.2.8 on 2026-03-16 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0041_student_extra_teachers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='photo',
            field=models.ImageField(blank=True, default='images/default-avatar.png', null=True, upload_to='teacher_photos/'),
        ),
    ]
