# Generated by Django 5.2.8 on 2026-03-20 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0044_alter_teacherprofile_photo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TeacherProfile',
        ),
        migrations.AddField(
            model_name='academicreport',
            name='year',
            field=models.PositiveIntegerField(default=2026),
        ),
    ]
