# Generated by Django 5.2.8 on 2026-03-20 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0045_delete_teacherprofile_academicreport_year'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='academicreport',
            unique_together={('student', 'year', 'term', 'exam_type')},
        ),
    ]
