# Generated by Django 5.2.8 on 2026-04-07 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0046_alter_academicreport_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassMinimumSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_level', models.CharField(max_length=20, unique=True)),
                ('minimum_subjects', models.IntegerField(default=7)),
            ],
        ),
    ]
