# Generated by Django 5.2.8 on 2026-04-09 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0047_classminimumsubject'),
    ]

    operations = [
        migrations.AddField(
            model_name='academicreport',
            name='overall_position',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='academicreport',
            name='stream_position',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='academicreport',
            name='total_points',
            field=models.IntegerField(default=0),
        ),
    ]
