# Generated by Django 5.2.8 on 2026-04-11 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0048_academicreport_overall_position_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='stream',
            field=models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=10, null=True),
        ),
    ]
