# Generated by Django 5.2.8 on 2026-04-11 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0049_student_stream'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportsubject',
            name='dev',
            field=models.IntegerField(default=0),
        ),
    ]
