# Generated by Django 5.2.8 on 2026-04-11 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0050_reportsubject_dev'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academicreport',
            name='teacher_comment',
            field=models.TextField(blank=True),
        ),
    ]
