# Generated by Django 5.2.8 on 2026-04-12 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0052_classteacher_subjectteacher'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('principal_name', models.CharField(max_length=200)),
                ('principal_signature', models.ImageField(blank=True, null=True, upload_to='principal_signatures/')),
            ],
        ),
    ]
