# Generated by Django 5.2.8 on 2025-12-15 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('students', '0008_remove_feestructure_school_remove_payment_school_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='school',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.DeleteModel(
            name='School',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
