from reportlab.platypus import (
    SimpleDocTemplate, Table, TableStyle, Image,
    Paragraph, Spacer
)
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.enums import TA_CENTER, TA_LEFT
from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.units import inch
from django.conf import settings
import os
from reportlab.pdfgen import canvas
from reportlab.lib.units import cm
from reportlab.lib.utils import ImageReader
from reportlab.graphics.barcode import qr
from reportlab.graphics.shapes import Drawing

# ============================================================
# 1. RECEIPT PDF – hii iko sawa, nimeiweka pekee yake
# ============================================================

def generate_receipt_pdf(file_path, student, payment):

    c = canvas.Canvas(file_path, pagesize=A4)
    width, height = A4

    # =======================================
    # HEADER BAR (Full width professional bar)
    # =======================================
    c.setFillColorRGB(0.15, 0.15, 0.30)  # Dark navy blue
    c.rect(0, height - 3*cm, width, 3*cm, fill=True, stroke=False)

    c.setFillColor(colors.white)
    c.setFont("Helvetica-Bold", 22)
    c.drawCentredString(width/2, height - 1.5*cm, "STUDENT PAYMENT RECEIPT")

    # =======================================
    # OPTIONAL LOGO (right side)
    # =======================================
    logo_path = os.path.join(settings.BASE_DIR, "static", "images", "logo.jpg")
    if os.path.exists(logo_path):
        try:
            logo = ImageReader(logo_path)
            c.drawImage(logo, width - 3.5*cm, height - 2.8*cm,
                        width=2.5*cm, height=2.5*cm, preserveAspectRatio=True)
        except:
            pass

    # Space under header
    y = height - 4.2*cm

    # =======================================
    # STUDENT INFORMATION (left block)
    # =======================================
    c.setFillColor(colors.black)
    c.setFont("Helvetica-Bold", 14)
    c.drawString(2*cm, y, "STUDENT INFORMATION")
    y -= 0.4*cm

    c.setLineWidth(0.8)
    c.setStrokeColor(colors.black)
    c.line(2*cm, y, width - 2*cm, y)
    y -= 1*cm

    c.setFont("Helvetica", 12)
    c.drawString(2*cm, y, f"Name: {student.full_name}")
    y -= 0.8*cm

    c.drawString(2*cm, y, f"Class Level: {student.class_level}")
    y -= 1.4*cm

    # =======================================
    # PAYMENT BOX (professional container)
    # =======================================
    c.setFont("Helvetica-Bold", 14)
    c.drawString(2*cm, y, "PAYMENT DETAILS")
    y -= 0.4*cm

    c.setLineWidth(1)
    c.setStrokeColor(colors.black)
    c.line(2*cm, y, width - 2*cm, y)
    y -= 1*cm

    # Box background
    c.setFillColorRGB(0.95, 0.95, 0.95)
    c.rect(2*cm, y - 4*cm, width - 4*cm, 4*cm, fill=True, stroke=False)

    # Payment details inside box
    c.setFillColor(colors.black)
    c.setFont("Helvetica", 12)

    inner_y = y - 0.8*cm

    c.drawString(2.5*cm, inner_y, f"Amount Paid:     Ksh {payment.amount_paid:,.2f}")
    inner_y -= 0.8*cm

    c.drawString(2.5*cm, inner_y, f"Payment Date:    {payment.date_paid.strftime('%Y-%m-%d %H:%M')}")
    inner_y -= 0.8*cm

    c.drawString(2.5*cm, inner_y, f"Payment Method:  {payment.method}")

    y = y - 5.5*cm  # move below box

    # =======================================
    # FOOTER
    # =======================================
    c.setStrokeColor(colors.gray)
    c.setLineWidth(0.5)
    c.line(2*cm, 2.2*cm, width - 2*cm, 2.2*cm)

    c.setFont("Helvetica-Oblique", 10)
    c.setFillColor(colors.gray)
    c.drawCentredString(width/2, 1.5*cm, "Generated by Students CB System")

    c.showPage()
    c.save()

# ============================================================
# 2. REUSABLE HEADER (Statement Header)
# ============================================================

def pdf_header(story):
    styles = getSampleStyleSheet()

    # ---------- LOAD LOGO ----------
    try:
        logo = Image("static/images/logo.jpg", width=70, height=70)
    except:
        logo = Paragraph("<b>[School Logo]</b>", styles["Normal"])

    # ---------- LEFT CONTACT STYLE ----------
    left_style = ParagraphStyle(
        "left_style",
        parent=styles["Normal"],
        fontSize=10,
        leading=14
    )

    left_block = [
        Paragraph("<b>Phone:</b> +254 712 345 678", left_style),
        Paragraph("<b>Email:</b> school@gmail.com", left_style),
        Paragraph("<b>Location:</b> Nairobi, Kenya", left_style),
    ]

    # ---------- SCHOOL NAME ----------
    school_name_style = ParagraphStyle(
        "school_name",
        parent=styles["Heading1"],
        fontSize=18,
        alignment=TA_CENTER,
        leading=22
    )

    school_name_block = [
        Paragraph("NAME <br/>SCHOOL", school_name_style)
    ]

    # ---------- TOP HEADER (3 columns) ----------
    header_table = Table(
        [[left_block, school_name_block, logo]],
        colWidths=[180, 200, 80]
    )

    header_table.setStyle(TableStyle([
        ("VALIGN", (0,0), (-1,-1), "MIDDLE"),
        ("BOTTOMPADDING", (0,0), (-1,-1), 5),
        ("TOPPADDING", (0,0), (-1,-1), 5),
    ]))

    story.append(header_table)
    story.append(Spacer(1, 5))

    # ---------- NAVY BAR INSIDE HEADER ----------
    navy_bar = Table(
        [[Paragraph(
            "<b>STUDENT FEE STATEMENT</b>",
            ParagraphStyle(
                "title_white",
                parent=styles["Heading2"],
                fontSize=13,
                textColor=colors.white,
                alignment=TA_CENTER,
                leading=14
            )
        )]],
        colWidths=[450]
    )

    navy_bar.setStyle(TableStyle([
        ("BACKGROUND", (0,0), (-1,-1), colors.darkblue),
        ("TOPPADDING", (0,0), (-1,-1), 8),
        ("BOTTOMPADDING", (0,0), (-1,-1), 8),
    ]))

    story.append(navy_bar)
    story.append(Spacer(1, 20))


# ============================================================
# 3. MAIN STUDENT STATEMENT PDF
# ============================================================
def generate_student_statement_pdf(file_path, student, payments, total_paid, total_fee, balance):
    styles = getSampleStyleSheet()
    story = []

    # HEADER (unchanged)
    pdf_header(story)


        # --- PROFILE TITLE WITH LINE ---
    profile_table = Table(
        [["PROFILE"]],
        colWidths=[450],
    )
    profile_table.setStyle(TableStyle([
        ('FONTNAME', (0, 0), (-1, -1), 'Helvetica-Bold'),
        ('FONTSIZE', (0, 0), (0, 0), 11),
        ('TEXTCOLOR', (0, 0), (0, 0), colors.HexColor("#222222")),
        ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
        ('BOTTOMPADDING', (0, 0), (0, 0), 8),
        ('TOPPADDING', (0, 0), (0, 0), 8),
        ('LINEBELOW', (0, 0), (0, 0), 1, colors.black),
    ]))

    story.append(profile_table)
    story.append(Spacer(1, 15))


    # ===============================
    # BEAUTIFUL STUDENT INFO BLOCK
    # ===============================
    info_style = ParagraphStyle(
        "info_style",
        parent=styles["BodyText"],
        fontSize=11,
        leading=16
    )

    student_info = [
        [Paragraph(f"<b>FULL NAME:</b> {student.full_name}", info_style)],
        [Paragraph(f"<b>ADMISSION NO:</b> {student.admission_number}", info_style)],
        [Paragraph(f"<b>CLASS:</b> {student.class_name}", info_style)],
    ]

    info_table = Table(student_info, colWidths=[400])
    info_table.setStyle(TableStyle([
        ("BOX", (0,0), (-1,-1), 1, colors.black),
        ("BACKGROUND", (0,0), (-1,0), colors.whitesmoke),
        ("LEFTPADDING", (0,0), (-1,-1), 10),
        ("RIGHTPADDING", (0,0), (-1,-1), 10),
        ("TOPPADDING", (0,0), (-1,-1), 6),
        ("BOTTOMPADDING", (0,0), (-1,-1), 6),
    ]))

    story.append(info_table)
    story.append(Spacer(1, 20))

    # ===============================
    # IMPROVED SUMMARY TABLE
    # ===============================
    summary_data = [
        ["DESCRIPTION", "AMOUNT"],
        ["Total Fee", f"Ksh {total_fee}"],
        ["Total Paid", f"Ksh {total_paid}"],
        ["Balance", f"Ksh {balance}"],
    ]

    summary_table = Table(summary_data, colWidths=[200, 200])
    summary_table.setStyle(TableStyle([
        ("BACKGROUND", (0,0), (-1,0), colors.lightgrey),
        ("TEXTCOLOR", (0,0), (-1,0), colors.black),
        ("FONTNAME", (0,0), (-1,0), "Helvetica-Bold"),
        ("GRID", (0,0), (-1,-1), 1, colors.black),
        ("ALIGN", (1,1), (-1,-1), "RIGHT"),
        ("BOTTOMPADDING", (0,0), (-1,-1), 8),
        ("TOPPADDING", (0,0), (-1,-1), 8),
        
    ]))

    story.append(summary_table)
    story.append(Spacer(1, 20))


# PAYMENT HISTORY TABLE
    payment_data = [["Date", "Amount", "Method", "Notes"]]

    for p in payments:
     payment_data.append([
        p.date_paid.strftime("%d-%m-%Y"),
        f"Ksh {p.amount_paid}",
        p.method,
        p.notes or ""
    ])

    pay_table = Table(payment_data, colWidths=[90, 120, 100, 90])
    pay_table.setStyle(TableStyle([
        ("BACKGROUND", (0,0), (-1,0), colors.lightgrey),
        ("TEXTCOLOR", (0,0), (-1,0), colors.black),
        ("FONTNAME", (0,0), (-1,0), "Helvetica-Bold"),
        ("GRID", (0,0), (-1,-1), 1, colors.black),
        ("ALIGN", (1,1), (-1,-1), "LEFT"),
        ("BOTTOMPADDING", (0,0), (-1,-1), 8),
        ("TOPPADDING", (0,0), (-1,-1), 8),
        
    ]))


    story.append(pay_table)
    story.append(Spacer(1, 20))


    # ===================================================
    # 🟦 PROFILE BAR + QR CODE + SIGNATURES SECTION
    # ===================================================
    
    qr_code = qr.QrCodeWidget(f"Student: {student.full_name}, Adm: {student.admission_number}")
    bounds = qr_code.getBounds()
    size = 70
    qr_drawing = Drawing(size, size)
    qr_drawing.add(qr_code)

    signature_text = "Parent/Guardian Signature: ________________________________"
    sig_qr_table = Table(
    [[signature_text, qr_drawing]],
    colWidths=[320, 100]
    )
    sig_qr_table.setStyle(TableStyle([
       ('FONTNAME', (0,0), (0,0), 'Helvetica'),
       ('FONTSIZE', (0,0), (0,0), 10),
       ('VALIGN', (0,0), (-1,-1), 'MIDDLE'),
       ('ALIGN', (1,0), (1,0), 'RIGHT'),  # QR right side
       ('LEFTPADDING', (0,0), (-1,-1), 5),
       ('RIGHTPADDING', (0,0), (-1,-1), 5),
    ]))

    story.append(sig_qr_table)

    story.append(Spacer(1, 25))

    # --- SIGNATURE LINES ---
    account_sig = Table(
         [["HDSignature: ________________________________"]],
        colWidths=[450]
    )
    account_sig.setStyle(TableStyle([
        ('FONTNAME', (0,0), (-1,-1), 'Helvetica'),
        ('FONTSIZE', (0,0), (-1,-1), 10),
        ('TOPPADDING', (0,0), (-1,-1), 10),
        ('BOTTOMPADDING', (0,0), (-1,-1), 10),
    ]))

    story.append(account_sig)
    # FINAL SAVE
    doc = SimpleDocTemplate(file_path, pagesize=A4)
    doc.build(story)


