# Generated by Django 5.2.8 on 2026-01-16 11:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0002_alter_timetable_subject_delete_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetable',
            name='class_level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetables', to='timetable.classlevel'),
        ),
    ]
