# Generated by Django 5.2.8 on 2026-01-16 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0003_alter_timetable_class_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetable',
            name='class_level',
            field=models.CharField(choices=[('Grade1', 'Grade1'), ('Grade2', 'Grade2'), ('Grade3', 'Grade3'), ('Grade4', 'Grade4'), ('Grade5', 'Grade5'), ('Grade6', 'Grade6'), ('Grade7', 'Grade7'), ('Grade8', 'Grade8'), ('Form1', 'Form1'), ('Form2', 'Form2'), ('Form3', 'Form3'), ('Form4', 'Form4')], max_length=50),
        ),
        migrations.DeleteModel(
            name='ClassLevel',
        ),
    ]
