# Generated by Django 5.2.8 on 2026-01-31 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0004_alter_timetable_class_level_delete_classlevel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetable',
            name='class_level',
            field=models.CharField(choices=[('Grade1', 'Grade1'), ('Grade2', 'Grade2'), ('Grade3', 'Grade3'), ('Grade4', 'Grade4'), ('Grade5', 'Grade5'), ('Grade6', 'Grade6'), ('Grade7', 'Grade7'), ('Grade8', 'Grade8'), ('Grade9', 'Grade9'), ('Grade10', 'Grade10'), ('Form3', 'Form3'), ('Form4', 'Form4')], max_length=50),
        ),
    ]
