# Generated by Django 5.2.8 on 2026-02-03 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0005_alter_timetable_class_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timetable',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='timetable',
            name='start_time',
        ),
        migrations.AddField(
            model_name='timetable',
            name='period',
            field=models.IntegerField(choices=[(1, 'Period 1'), (2, 'Period 2'), (3, 'Short Break'), (4, 'Period 3'), (5, 'Tea Break'), (6, 'Period 4'), (7, 'Lunch Break'), (8, 'Period 5'), (9, 'Short Break'), (10, 'Period 6')], default=1),
            preserve_default=False,
        ),
    ]
