# Generated by Django 5.2.8 on 2026-02-05 08:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0006_remove_timetable_end_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timetable',
            name='period',
        ),
        migrations.AddField(
            model_name='timetable',
            name='end_time',
            field=models.TimeField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='timetable',
            name='start_time',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
